### PR TITLE
Compatible linked modules

### PR DESCRIPTION
**Pull request by TongChia**

### CODE REVIEW

**Comment by weblogixx** [comment]
Hi @TongChia,

thank you for this pr. It seems good to me.

@sthzg: What is your opinion on this? I think it would make it easier with linked modules.

**Comment by sthzg** [comment]
Tbh, I am embarrassed to admit that I have never included external sources to the loaders this way 😓 , so I feel that I don't have enough experience to say sth. about it. Running the path through `realpath` seems fine to me. @TongChia did you run into bugs/problems without it?

@weblogixx with 'easier with linked modules', do you mean that this way modules don't necessarily have to be `npm link`ed to be available?

**Comment by weblogixx** [comment]
@sthzg, yes, that is correct. Basically you could just use ```ln -s```in your node_modules folder with this fix and would not be found to npm link (which, honestly, doesn`t work the way some people want it anyways).

**Comment by sthzg** [comment]
Ah, got it. Unless putting it into package.json as a dep, wouldn't npm (as well as the airbnb rules) report an error about an extraneous package? But I get the point and it probably may be configured  as an exception.

**Comment by TongChia** [comment]
Sorry for late reply @sthzg @weblogixx 
yes, I have been working with it for some time under ubuntu (node 4.5.0) and mac (node 6.3.0).

when we use `npm link ../dev-module --save` it would be a dep. but `node_modules/dev-module` is a soft link equivalent to a file. so `import 'dev-module/component'` Invalid.
`fs.realpathSync(...)` will return the real path whatever it's a link or ture path. so it's harmless~
(⌒ . ⌒)☆

**Comment by weblogixx** [comment]
Yes, thats the way I would use it, too. If there are no other issues, I think we should merge this.
@sthzg: Your opinion on this?

**Comment by sthzg** [comment]
@TongChia thanks for clarifying and the contribution!
@weblogixx sure, let's merge.

**Pull request merged**
